#!/bin/sh
echo do-nothing - started
node do-nothing
echo do-nothing - finished

echo do-almost-nothing - started
node do-almost-nothing
echo do-almost-nothing - finished

echo one-shot - started
echo | node one-shot
echo one-shot - finished

echo two-shot - started
echo | node two-shot
echo two-shot - finished

# brute-force-leak-check takes a while to execute so its only run occasionally
#echo brute-force-leak-check - started
#echo | node brute-force-leak-check
#echo brute-force-leak-check - finished

echo performance-check - started
echo | node performance-check
echo performance-check - finished

