language: node_js
node_js:
  - "14"
  - "13"
  - "12"
  - "10"
  - "8"
env:
  - CXX=g++-6.3
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6.3
script:
  - npm run lint
  - npm test

